## 2 - A

In [2]:
id = input("Student's ID: ")
tutorialMark = eval(input("Student's tutorial mark: "))
testMark = eval(input("Student's test mark: "))

if (tutorialMark+testMark)/2 < 40:
    print("Student's ID: ", id, "and Grade: F")
else:
    examMark = eval(input("Student's exam-mark: "))
    tutorialMark = tutorialMark * .25
    testMark = testMark * .25
    examMark = examMark * .5
    finalMarks = examMark + tutorialMark + testMark
    
    if finalMarks in range(80, 101):
        print("Student's ID: ", id, "and Grade: A")
    elif finalMarks in range(70, 80):
        print("Student's ID: ", id, "and Grade: B")
    elif finalMarks in range(60, 70):
        print("Student's ID: ", id, "and Grade: C")
    elif finalMarks in range(50, 60):
        print("Student's ID: ", id, "and Grade: D")
    elif finalMarks < 50:
        print("Student's ID: ", id, "and Grade: E")

Student's ID: 072
Student's tutorial mark: 88
Student's test mark: 88
Student's exam-mark: 88
Student's ID:  072 and Grade: A


## 2. B.

In [2]:
print("Input lengths of the triangle sides: ")
x = eval(input("x: "))
y = eval(input("y: "))
z = eval(input("z: "))
if x==y==z:
    print("Equilateral triangle")
elif x!=y and y!=z and x!=z:
    print("Scalene triangle")
else:
    print("Isosceles triangle")

Input lengths of the triangle sides: 
x: 2
y: 5
z: 2
Isosceles triangle


## 2. C

In [ ]:
for i in range(1500, 2701):
    if i%7==0 and i%5==0:
        print(i)

## 3. A

In [ ]:
# Didn't take time, Just Copied from Zobaer Ul Islam (https://bit.ly/2QoM2JL)
#Category List
print("1: Publicly Traded Company")
print("2: Non-Publicly Traded Company")
print("3: Publicly Traded Cigarette Company")
print("4: Mobile Phone Operator Company")
print("5: Publicly Traded Mobile Phone Company")

#Inputs
taxpayerCategory = eval(input("Enter Your Category Number: "))

#Calculating Tax Amount#

# 1. Publicly Traded Company
if taxpayerCategory == 1:
    dividendRate = eval(input("Did The Publicly Traded Company Declare Dividend? If Yes Then Enter the Rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if dividendRate == 0:
        if profitAmount>1000000:
            netTax = profitAmount*.275
        elif profitAmount < 1000000:
            netTax = profitAmount*.255
    elif dividendRate > 30:
        if profitAmount>1000000:
            netTax = profitAmount*.2475
        elif profitAmount < 1000000:
            netTax = profitAmount*.2075
    elif dividendRate < 10:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.30

# 2. Non Publicly Traded Company
if taxpayerCategory == 2:
    paidupCapitalThroughIPO = eval(input("How Much Share of your Paid Up Capital was Transfered through IPO? Enter the rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if paidupCapitalThroughIPO >= 20:
        if profitAmount>1000000:
            taxBeforeRebate = profitAmount*.35
            netTax = taxBeforeRebate  - taxBeforeRebate*.10
        elif profitAmount < 1000000:
            taxBeforeRebate = profitAmount*.32
            netTax = taxBeforeRebate  - taxBeforeRebate*.10
    else:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.32

# 3. Publicly Traded Cigarette Company
if taxpayerCategory == 3:
    dividendRate = eval(input("Did The Publicly Traded Cigarette Company Declare Dividend? If Yes Then Enter the Rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if dividendRate == 0:
        if profitAmount>1000000:
            netTax = profitAmount*.40
        elif profitAmount < 1000000:
            netTax = profitAmount*.35
    elif dividendRate > 30:
        if profitAmount>1000000:
            netTax = profitAmount*.2475
        elif profitAmount < 1000000:
            netTax = profitAmount*.2075
    elif dividendRate < 10:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.30
            
# 4. Mobile Phone Operator Company
if taxpayerCategory == 4:
    profitAmount = eval(input("Enter The Profit Amount: "))
    if profitAmount>1000000:
        netTax = profitAmount*.45
    elif profitAmount < 1000000:
        netTax = profitAmount*.40

# 5. Publicly Traded Mobile Company
if taxpayerCategory == 5:
    dividendRate = eval(input("Did The Publicly Traded Mobile Company Declare Dividend? If Yes Then Enter the Rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if dividendRate == 0:
        if profitAmount>1000000:
            netTax = profitAmount*.40
        elif profitAmount < 1000000:
            netTax = profitAmount*.35
    elif dividendRate > 30:
        if profitAmount>1000000:
            netTax = profitAmount*.2475
        elif profitAmount < 1000000:
            netTax = profitAmount*.2075
    elif dividendRate < 10:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.30
            
#Print Tax Amount            
print("Net Tax For The Company is: ",round(netTax,2))

## 3.B

In [4]:
def presentValue(f, r, n):
    p = f / pow((1 + r), n)
    return p
    
f = eval(input("Enter final account value: "))
r = eval(input("Enter annual interest rate in percent: "))
n = eval(input("Enter number of years: "))
r=r/100
presentValue = round(presentValue(f, r, n), 2)
print("Initial deposit value/Present value is: ",presentValue)

Enter final account value: 10000
Enter annual interest rate in percent: 4.2
Enter number of years: 10
Initial deposit value/Present value is:  6627.09


## 4. B

In [5]:
""" There is a problem in this question. The shipping cost for packages in range of 21-50 pounds is not mentioned. 
That's why I have extended the range from 10-20 to 10-50"""

w = eval(input("The weight of the package (in pounds): "))
if w>0 and w<=1:
    print("The shipping cost is: $3.5")
elif w>1 and w<=3:
    print("The shipping cost is: $5.5")
elif w>3 and w<=10:
    print("The shipping cost is: $8.5")
elif w>10 and w<=50:
    print("The shipping cost is: $10.5")
elif w>50:
    print("The package cannot be shipped")

The weight of the package (in pounds): 15
The shipping cost is: $10.5


## 4. C

In [ ]:
demand = eval(input("Demand Rate (i.e., 16,000 units): "))
setup_cost = eval(input("The setup cost is (i.e., BDT 50: "))
holding_cost = eval(input("The holding cost per item (i.e., BDT 2.5): "))

eoq = ((2 * demand * setup_cost)/holding_cost)**0.5
print("According to the provided data the EOQ is:", eoq)

## 5. A

In [5]:
import numpy as np
x = np.array([[1, 2, 3, 4],
            [4, 5, 6, 5],
            [7, 8, 9, 6],
            [3, 4, 5, 7]])

In [6]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 5],
       [7, 8, 9, 6],
       [3, 4, 5, 7]])

In [7]:
#(i)
x[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8],
       [3, 4]])

In [8]:
#(ii)
x[1, :2]

array([4, 5])

In [9]:
#(iii)
x[3, :]

array([3, 4, 5, 7])

In [10]:
#(iv)
x[:3, 2:]

array([[3, 4],
       [6, 5],
       [9, 6]])

## 6 - A

In [ ]:
savingsAmount = eval(input("Enter the monthly savings amount: "))

months = 6
monthlyIntRate = 5/100/12

totalSavings = 0

for i in range(months):
    totalSavings = (savingsAmount + totalSavings)*(1+monthlyIntRate)
print("At {0}% annual interest rate, with the monthly savings of ${1} for {2} months, the amount in the savings account will be ${3}.".format(annualIntRate, savingsAmount, months,round(totalSavings, 2)))


## 6 - C

In [1]:
import pandas as pd
data =[{'Age': 25, 'Name': 'tom', 'Rating': 4.23}, 
       {'Age':26, 'Name': 'James', 'Rating': 3.24 },
       {'Age':25, 'Name': 'James', 'Rating': 3.98},
       {'Age': 25, 'Name': 'Ricky', "Rating": 3.98}
      ]
df = pd.DataFrame(data)
df

Age   Name  Rating
0   25    tom    4.23
1   26  James    3.24
2   25  James    3.98
3   25  Ricky    3.98

In [2]:
df.describe()

Age    Rating
count   4.00  4.000000
mean   25.25  3.857500
std     0.50  0.428204
min    25.00  3.240000
25%    25.00  3.795000
50%    25.00  3.980000
75%    25.25  4.042500
max    26.00  4.230000