# Question 5 - A

In [1]:
import numpy as np
x = np.array([[1, 2, 3, 4],
            [4, 5, 6, 5],
            [7, 8, 9, 6],
            [3, 4, 5, 7]])

In [2]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 5],
       [7, 8, 9, 6],
       [3, 4, 5, 7]])

In [3]:
x[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8],
       [3, 4]])

In [4]:
x[1,:2]

array([4, 5])

In [5]:
x[3,:]

array([3, 4, 5, 7])

In [6]:
x[:3,2:]

array([[3, 4],
       [6, 5],
       [9, 6]])

# Question 6 - C

In [7]:
import pandas as pd
data =[{'Age': 25, 'Name': 'tom', 'Rating': 4.23}, 
       {'Age':26, 'Name': 'James', 'Rating': 3.24 },
       {'Age':25, 'Name': 'James', 'Rating': 3.98},
       {'Age': 25, 'Name': 'Ricky', "Rating": 3.98}
      ]
df = pd.DataFrame(data)
df

Age   Name  Rating
0   25    tom    4.23
1   26  James    3.24
2   25  James    3.98
3   25  Ricky    3.98

In [8]:
df.describe()

Age    Rating
count   4.00  4.000000
mean   25.25  3.857500
std     0.50  0.428204
min    25.00  3.240000
25%    25.00  3.795000
50%    25.00  3.980000
75%    25.25  4.042500
max    26.00  4.230000