## Question - 1

In [9]:
# Didn't take time, Just Copied from Zobaer Ul Islam (https://bit.ly/2QoM2JL)
#Category List
print("1: Publicly Traded Company")
print("2: Non-Publicly Traded Company")
print("3: Publicly Traded Cigarette Company")
print("4: Mobile Phone Operator Company")
print("5: Publicly Traded Mobile Phone Company")

#Inputs
taxpayerCategory = eval(input("Enter Your Category Number: "))

#Calculating Tax Amount#

# 1. Publicly Traded Company
if taxpayerCategory == 1:
    dividendRate = eval(input("Did The Publicly Traded Company Declare Dividend? If Yes Then Enter the Rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if dividendRate == 0:
        if profitAmount>1000000:
            netTax = profitAmount*.275
        elif profitAmount < 1000000:
            netTax = profitAmount*.255
    elif dividendRate > 30:
        if profitAmount>1000000:
            netTax = profitAmount*.2475
        elif profitAmount < 1000000:
            netTax = profitAmount*.2075
    elif dividendRate < 10:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.30

# 2. Non Publicly Traded Company
if taxpayerCategory == 2:
    paidupCapitalThroughIPO = eval(input("How Much Share of your Paid Up Capital was Transfered through IPO? Enter the rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if paidupCapitalThroughIPO >= 20:
        if profitAmount>1000000:
            taxBeforeRebate = profitAmount*.35
            netTax = taxBeforeRebate  - taxBeforeRebate*.10
        elif profitAmount < 1000000:
            taxBeforeRebate = profitAmount*.32
            netTax = taxBeforeRebate  - taxBeforeRebate*.10
    else:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.32

# 3. Publicly Traded Cigarette Company
if taxpayerCategory == 3:
    dividendRate = eval(input("Did The Publicly Traded Cigarette Company Declare Dividend? If Yes Then Enter the Rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if dividendRate == 0:
        if profitAmount>1000000:
            netTax = profitAmount*.40
        elif profitAmount < 1000000:
            netTax = profitAmount*.35
    elif dividendRate > 30:
        if profitAmount>1000000:
            netTax = profitAmount*.2475
        elif profitAmount < 1000000:
            netTax = profitAmount*.2075
    elif dividendRate < 10:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.30
            
# 4. Mobile Phone Operator Company
if taxpayerCategory == 4:
    profitAmount = eval(input("Enter The Profit Amount: "))
    if profitAmount>1000000:
        netTax = profitAmount*.45
    elif profitAmount < 1000000:
        netTax = profitAmount*.40

# 5. Publicly Traded Mobile Company
if taxpayerCategory == 5:
    dividendRate = eval(input("Did The Publicly Traded Mobile Company Declare Dividend? If Yes Then Enter the Rate in %: "))
    profitAmount = eval(input("Enter The Profit Amount: "))
    if dividendRate == 0:
        if profitAmount>1000000:
            netTax = profitAmount*.40
        elif profitAmount < 1000000:
            netTax = profitAmount*.35
    elif dividendRate > 30:
        if profitAmount>1000000:
            netTax = profitAmount*.2475
        elif profitAmount < 1000000:
            netTax = profitAmount*.2075
    elif dividendRate < 10:
        if profitAmount>1000000:
            netTax = profitAmount*.35
        elif profitAmount < 1000000:
            netTax = profitAmount*.30
            
#Print Tax Amount            
print("Net Tax For The Company is: ",round(netTax,2))

1: Publicly Traded Company
2: Non-Publicly Traded Company
3: Publicly Traded Cigarette Company
4: Mobile Phone Operator Company
5: Publicly Traded Mobile Phone Company
Enter Your Category Number: 1
Did The Publicly Traded Company Declare Dividend? If Yes Then Enter the Rate in %: 40
Enter The Profit Amount: 13000000
Net Tax For The Company is:  3217500.0


## Question - 2

In [6]:
def presentValue(f, r, n):
    p = f / pow((1 + r), n)
    return p
    
f = eval(input("Enter final account value: "))
r = eval(input("Enter annual interest rate in percent: "))
n = eval(input("Enter number of years: "))
r=r/100
presentValue = round(presentValue(f, r, n), 2)
print("Initial deposit value/Present value is: ",presentValue)

Enter final account value: 10000
Enter annual interest rate in percent: 1
Enter number of years: 5
Initial deposit value/Present value is:  9514.66


## Question - 3

In [ ]:
Question e ektu ghapla ache

## Question - 4

In [ ]:
demand = eval(input("Demand Rate (i.e., 16,000 units): "))
setup_cost = eval(input("The setup cost is (i.e., BDT 50: "))
holding_cost = eval(input("The holding cost per item (i.e., BDT 2.5): "))

eoq = ((2 * demand * setup_cost)/holding_cost)**0.5
print("According to the provided data the EOQ is:", eoq)

## Question - 5

In [10]:
savingsAmount = eval(input("Enter the monthly savings amount: "))

months = 6
monthlyIntRate = 5/100/12

totalSavings = 0

for i in range(months):
    totalSavings = (savingsAmount + totalSavings)*(1+monthlyIntRate)
print("At {0}% annual interest rate, with the monthly savings of ${1} for {2} months, the amount in the savings account will be ${3}.".format(annualIntRate, savingsAmount, months,round(totalSavings, 2)))

Enter the monthly savings amount: 100
At 5% annual interest rate, with the monthly savings of $100 for 6 months, the amount in the savings account will be $608.81.


## Question - 6

In [ ]:
store_1 = eval(input("Enter today's total sales for store one (rounded to nearest $100): "))
store_2 = eval(input("Enter today's total sales for store two (rounded to nearest $100): "))
store_3 = eval(input("Enter today's total sales for store three (rounded to nearest $100): "))

for i in range(0,store_1, 100):
    print("*", end="")
print()
for j in range(0,store_2,100):
    print("*", end="")
print()
for k in range(0, store_3, 100):
    print("*", end="")
© 2019 GitHub, Inc.

## Question - 7

In [12]:
def calculateCharge (weight, distance) :
    if weight < 0:
        return "Weight Cannot be less than or equal to ZERO"
    elif weight <= 2 and weight > 0:
        rate = 3.1
    elif weight <= 6:
        rate = 4.2
    elif weight <= 10:
        rate = 5.30
    else:
        rate = 6.40
    
    shippingCharge = rate*distance
    print("The shipping charge of your package is: ", shippingCharge)

weight = eval(input("Enter the weight of your package (in kilograms): "))
distance = eval(input("Enter the distance it is to be shipped (in miles): "))
calculateCharge(weight, distance)



Enter the weight of your package (in kilograms): 8
Enter the distance it is to be shipped (in miles): 10
The shipping charge of your package is:  53.0


## Question - 8

In [ ]:
total_occupied = 0
for floor in range(10, 17):
    if floor == 13:
        continue
    num_of_suits = int(input("How many suits are occupied in floor {0} : ".format(floor)))
    if num_of_suits not in range(0, 21):
        num_of_suits = int(input("Enter the value between 0 and 20 : ".format(floor)))
    total_occupied = total_occupied + num_of_suits
print("The total number of suits occupied =", total_occupied)

total_suits = 120
percent_of_occupancy = total_occupied * 100 / total_suits
print("The hotel has {0} suits, {1} of those are occupied. The percentage of them are occupied is {2}".format(total_suits,total_occupied,percent_of_occupancy))

## Question - 9

In [8]:
l = eval(input("Loan Amount: "))
rate = eval(input("Monthly Interest Rate: "))
rate = rate/100
n = eval(input("Number of Payments: "))

monthlyPayment = rate * pow(1+rate,n) * l / (pow(1+rate, n) - 1)
amountPaidBack = monthlyPayment * n
intPaid = amountPaidBack - l
print("Monthly Payment:", round(monthlyPayment, 2))
print("Amount Paid Back:", round(amountPaidBack,2))
print("Interest Paid: ", round(intPaid,2))

Loan Amount: 10000
Monthly Interest Rate: 1
Number of Payments: 36
Monthly Payment: 332.14
Amount Paid Back: 11957.15
Interest Paid:  1957.15


## Question - 10

In [13]:
def computeBill(hourlyRate, time, income):
    if income <= 25000:
        if time <= 30:
            bill = 0
        else:
            bill = (time-30)*hourlyRate*.4/60
    else:
        if time <= 20:
            bill = 0
        else:
            bill = (time-20)*hourlyRate*.7/60
    return bill
hourlyRate = eval(input("Enter the hourly rate: "))
time = eval(input("Enter the total consulting time in minutes: "))
income = eval(input("Enter the income amount: "))

bill = computeBill(hourlyRate, time, income)
print("Your total consulting bill is:", bill)

Enter the hourly rate: 70
Enter the total consulting time in minutes: 75
Enter the income amount: 1000
Your total consulting bill is: 21.0


## Question - 11

In [3]:
shares = 750
buying_price = 35
selling_price = 31.15
total_paid = shares*buying_price
total_received = shares*selling_price

print("The total amount paid for the stock: ", total_paid)
print("The total amount received from selling the stock: ", total_received)
print("The total amount of money she lost: ", total_paid-total_received)

The total amount paid for the stock:  26250
The total amount received from selling the stock:  23362.5
The total amount of money she lost:  2887.5


## Question - 12

In [1]:
"""Probably it's impossible to solve this problem without global variable following the general process.
It can be easily solved without global varial, if we go with class-object. But this topic was not taught I guess"""

"Probably it's impossible to solve this problem without global variable following the general process.\nIt can be easily solved without global varial, if we go with class-object. But this topic was not taught I guess"

## Question - 13

In [7]:
S_CUP = 9
M_CUP = 12
L_CUP = 15

S_PRICE = 1.75
M_PRICE = 1.90
L_PRICE = 2.00

s_size_total_sold = 4
m_size_total_sold = 0
l_size_total_sold = 0

total_sold_cups = 0
total_money_made = 0

#def use_program():
    
def sell_coffee():
    small = "small"
    medium = "medium"
    large = "large"
    size = eval(input("The cup size you want (small, medium, large): "))
    cups = int(input("The number of cups you want: "))
    if size == "small":
        price = cups * S_PRICE
    elif size == "medium":
        price = cups * M_PRICE
    elif size == "large":
        price = cups * L_PRICE
    else:
        print("Sorry, sir. We don't have this cup size. Try another")
    print(cups, ":", price)
    
    each_size_total_sold(size, cups)
def each_size_total_sold(size, cups):
    global s_size_total_sold
    global m_size_total_sold
    global l_size_total_sold
    if size == "small":
        s_size_total_sold = s_size_total_sold + cups
    elif size == "medium":
        m_size_total_sold = m_size_total_sold + cups
    elif size == "large":
        l_size_total_sold = l_size_total_sold + cups
    print(s_size_total_sold)
sell_coffee()

The cup size you want (small, medium, large): small
The number of cups you want: 4
4 : 7.0
8


## Question - 14

In [7]:
def sell_coffee():
    small = "small"
    medium = "medium"
    large = "large"
    size = eval(input("The cup size you want (small, medium, large): "))
    cups = int(input("The number of cups you want: "))
    if size == "small":
        price = cups * S_PRICE
    elif size == "medium":
        price = cups * M_PRICE
    elif size == "large":
        price = cups * L_PRICE
    else:
        print("Sorry, sir. We don't have this cup size. Try another")
    return price
sell_coffee()

The cup size you want (small, medium, large): small
The number of cups you want: 4


7.0

## Question 5 - A

In [18]:
import numpy as np
x = np.array([[1, 2, 3, 4],
            [4, 5, 6, 5],
            [7, 8, 9, 6],
            [3, 4, 5, 7]])

In [19]:
x[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8],
       [3, 4]])

In [20]:
x[1,:2]

array([4, 5])

In [21]:
x[3,:]

array([3, 4, 5, 7])

In [22]:
x[:3,2:]

array([[3, 4],
       [6, 5],
       [9, 6]])

In [1]:
import pandas as pd
data =[{'Age': 25, 'Name': 'tom', 'Rating': 4.23}, 
       {'Age':26, 'Name': 'James', 'Rating': 3.24 },
       {'Age':25, 'Name': 'James', 'Rating': 3.98},
       {'Age': 25, 'Name': 'Ricky', "Rating": 3.98}
      ]
df = pd.DataFrame(data)
df

Age   Name  Rating
0   25    tom    4.23
1   26  James    3.24
2   25  James    3.98
3   25  Ricky    3.98

In [2]:
df.describe()

Age    Rating
count   4.00  4.000000
mean   25.25  3.857500
std     0.50  0.428204
min    25.00  3.240000
25%    25.00  3.795000
50%    25.00  3.980000
75%    25.25  4.042500
max    26.00  4.230000

In [32]:
print("'Name',"*12)

'Name','Name','Name','Name','Name','Name','Name','Name','Name','Name','Name','Name',


In [41]:
#name02 = ["Tom', "James", 'Ricky', 'Vin', 'Steve', 'Smith', 'Jack', 'Lee', 'David', 'Gasper', 'Betina', 'Andres']
#age = [25,26, 25, 23, 30, 29, 23, 34, 40, 30, 51, 46]
#rating = [4.23, 3.24, 3.98, 2.56, 3.20, 4.60, 3.80, 3.78, 2.98, 4.80, 4.10, 3.65]

#name01 = ['Name','Name','Name','Name','Name','Name','Name','Name','Name','Name','Name','Name']
name = dict(zip(['Name','Name','Name','Name','Name','Name','Name','Name','Name','Name','Name','Name'],['Tom', 'James', 'Ricky', 'Vin', 'Steve', 'Smith', 'Jack', 'Lee', 'David', 'Gasper', 'Betina', 'Andres']))

In [42]:
name

{'Name': 'Andres'}

In [40]:
print(name)

{'Name': 'Andres'}


In [44]:
name = dict(zip([1,2,3], ['a', 'b', 'c']))

In [45]:
name

{1: 'a', 2: 'b', 3: 'c'}